/*
 * This source file was generated by the Gradle 'init' task
 */
package javatest;

public class App {
    public String getGreeting() {
        return "Hello w0rld!";
    }

    public static void sort(int[] unsortedArray) {
        int biggest = 0, biggestIdx = 0;
        int[] sortedArray = new int[unsortedArray.length];

        for (int jj = 0; jj < unsortedArray.length; jj++) {
            for (int ii = 0; ii < unsortedArray.length; ii++) {
                if (unsortedArray[ii] > biggest) {
                    biggest = Math.max(unsortedArray[ii], biggest);
                    biggestIdx = ii;
                }
            }
            sortedArray[biggestIdx] = 0;
            sortedArray[jj] = biggest;
            biggest = 0;
        }
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
